name: Docker - publish multi-arch packages

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}

      - name: Build Docker image and save as artifact
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false  # Don't push yet
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max,expires=2d
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          outputs: type=docker,name=ghcr-image.tar,dest=/tmp/image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/image.tar

  push-to-registries:
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load < docker-image.tar

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to ghcr.io
        run: |
          docker tag ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }} ghcr.io/${{ env.IMAGE_NAME }}
          docker push ghcr.io/${{ env.IMAGE_NAME }}

      - name: Log into registry docker.io
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Push Docker image to docker.io
        run: |
          docker tag ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }} docker.io/${{ env.IMAGE_NAME }}
          docker push docker.io/${{ env.IMAGE_NAME }}